spring.application.name=LogApi

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=Aluno
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

google.recaptcha.secret=6Ld3jIIsAAAAABlSfq7SIxKPiY3CtvzH0HSl6VEK
google.client.id=48867302798-cu3d9mpbmlmt9hepff9oc7cjqjs22fiq.apps.googleusercontent.com

server.port=8443

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=784512
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=logapi
server.ssl.enabled=true